serverFiles:
  alerting_rules.yml:
    groups:
      - name: NodeDown
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 5m
            labels:
              severity: page
            annotations:
              host: "{{ $labels.instance }}"
              summary: "Instance down"
              description: "Instance {{$labels.instance}} has been unreachable for more than 5 minutes."
      - name: low_memory_alert
        rules:
          - alert: LowMemory
            expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
            for: 2m
            labels:
              severity: warning
            annotations:
              host: "{{ $labels.instance }}"
              summary: "Low memory warning"
              description: "Memory usage on instance {{$labels.instance}} is below 20%."
          - alert: KubePersistentVolumeErrors
            expr: |
              kubelet_volume_stats_errors_total{job="kubelet"} > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              description: "PersistentVolume {{$labels.persistentvolume}} is having issues with provisioning."
              summary: "PersistentVolume provision issue"
          - alert: KubePodCrashLooping
            expr: |
              rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[5m]) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              description: "Pod {{$labels.pod}} is crash looping."
              summary: "Pod crash looping"
          - alert: KubePodNotReady
            expr: |
              kube_pod_status_phase{phase="Pending"} == 1
            for: 2m
            labels:
              severity: warning
            annotations:
              description: "Pod {{$labels.pod}} has been in a non-ready state for more than 2 minutes."
              summary: "Pod not ready"
